// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/proto/api.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter int32

const (
	Filter_NONE            Filter = 0
	Filter_ONLY_ACCEPTED   Filter = 1
	Filter_ONLY_CANDIDATES Filter = 2
	Filter_ONLY_REJECTED   Filter = 3
)

// Enum value maps for Filter.
var (
	Filter_name = map[int32]string{
		0: "NONE",
		1: "ONLY_ACCEPTED",
		2: "ONLY_CANDIDATES",
		3: "ONLY_REJECTED",
	}
	Filter_value = map[string]int32{
		"NONE":            0,
		"ONLY_ACCEPTED":   1,
		"ONLY_CANDIDATES": 2,
		"ONLY_REJECTED":   3,
	}
)

func (x Filter) Enum() *Filter {
	p := new(Filter)
	*p = x
	return p
}

func (x Filter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Filter) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_api_proto_enumTypes[0].Descriptor()
}

func (Filter) Type() protoreflect.EnumType {
	return &file_internal_proto_api_proto_enumTypes[0]
}

func (x Filter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Filter.Descriptor instead.
func (Filter) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0}
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        Filter                 `protobuf:"varint,1,opt,name=filter,proto3,enum=proto.Filter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *ListNodesRequest) GetFilter() Filter {
	if x != nil {
		return x.Filter
	}
	return Filter_NONE
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      []*NodeInfo            `protobuf:"bytes,1,rep,name=accepted,proto3" json:"accepted,omitempty"`
	Candidates    []*NodeInfo            `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Rejected      []*NodeInfo            `protobuf:"bytes,3,rep,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *ListNodesResponse) GetAccepted() []*NodeInfo {
	if x != nil {
		return x.Accepted
	}
	return nil
}

func (x *ListNodesResponse) GetCandidates() []*NodeInfo {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ListNodesResponse) GetRejected() []*NodeInfo {
	if x != nil {
		return x.Rejected
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       *string                `protobuf:"bytes,2,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Certificate   *string                `protobuf:"bytes,3,opt,name=certificate,proto3,oneof" json:"certificate,omitempty"`
	IsConnected   *bool                  `protobuf:"varint,4,opt,name=isConnected,proto3,oneof" json:"isConnected,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=since,proto3,oneof" json:"since,omitempty"`
	LastMsg       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=lastMsg,proto3,oneof" json:"lastMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *NodeInfo) GetCertificate() string {
	if x != nil && x.Certificate != nil {
		return *x.Certificate
	}
	return ""
}

func (x *NodeInfo) GetIsConnected() bool {
	if x != nil && x.IsConnected != nil {
		return *x.IsConnected
	}
	return false
}

func (x *NodeInfo) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *NodeInfo) GetLastMsg() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMsg
	}
	return nil
}

type NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *NodeRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type NodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *NodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type NodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodesResponse) Reset() {
	*x = NodesResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesResponse) ProtoMessage() {}

func (x *NodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesResponse.ProtoReflect.Descriptor instead.
func (*NodesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *NodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultID      string                 `protobuf:"bytes,1,opt,name=resultID,proto3" json:"resultID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultsRequest) Reset() {
	*x = ResultsRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsRequest) ProtoMessage() {}

func (x *ResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsRequest.ProtoReflect.Descriptor instead.
func (*ResultsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *ResultsRequest) GetResultID() string {
	if x != nil {
		return x.ResultID
	}
	return ""
}

type ResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // raw result, as stored in the DB (should be a serialized JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultsResponse) Reset() {
	*x = ResultsResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsResponse) ProtoMessage() {}

func (x *ResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsResponse.ProtoReflect.Descriptor instead.
func (*ResultsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *ResultsResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRequest) Reset() {
	*x = RequestRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRequest) ProtoMessage() {}

func (x *RequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRequest.ProtoReflect.Descriptor instead.
func (*RequestRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *RequestRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type RequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"` // raw request, as stored in the DB (should be a serialized JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestResponse) Reset() {
	*x = RequestResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResponse) ProtoMessage() {}

func (x *RequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResponse.ProtoReflect.Descriptor instead.
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *RequestResponse) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type ListResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`                           // Starting position for pagination (0-based)
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                             // Maximum number of results to return, defaults to 100 if not specified
	FromDate      *int64                 `protobuf:"varint,3,opt,name=from_date,json=fromDate,proto3,oneof" json:"from_date,omitempty"` // Optional Unix timestamp to filter results from this date
	ToDate        *int64                 `protobuf:"varint,4,opt,name=to_date,json=toDate,proto3,oneof" json:"to_date,omitempty"`       // Optional Unix timestamp to filter results up to this date
	Targets       []string               `protobuf:"bytes,5,rep,name=targets,proto3" json:"targets,omitempty"`                          // Optional list of node IDs to filter results by targets
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResultsRequest) Reset() {
	*x = ListResultsRequest{}
	mi := &file_internal_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResultsRequest) ProtoMessage() {}

func (x *ListResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResultsRequest.ProtoReflect.Descriptor instead.
func (*ListResultsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListResultsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListResultsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListResultsRequest) GetFromDate() int64 {
	if x != nil && x.FromDate != nil {
		return *x.FromDate
	}
	return 0
}

func (x *ListResultsRequest) GetToDate() int64 {
	if x != nil && x.ToDate != nil {
		return *x.ToDate
	}
	return 0
}

func (x *ListResultsRequest) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

type ResultEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // Status of the task (success, failed, error)
	InternalError InternalError          `protobuf:"varint,4,opt,name=internal_error,json=internalError,proto3,enum=proto.InternalError" json:"internal_error,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultEntry) Reset() {
	*x = ResultEntry{}
	mi := &file_internal_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultEntry) ProtoMessage() {}

func (x *ResultEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultEntry.ProtoReflect.Descriptor instead.
func (*ResultEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *ResultEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResultEntry) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ResultEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResultEntry) GetInternalError() InternalError {
	if x != nil {
		return x.InternalError
	}
	return InternalError_OK
}

func (x *ResultEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ResultEntry         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResultsResponse) Reset() {
	*x = ListResultsResponse{}
	mi := &file_internal_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResultsResponse) ProtoMessage() {}

func (x *ListResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResultsResponse.ProtoReflect.Descriptor instead.
func (*ListResultsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListResultsResponse) GetResults() []*ResultEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_internal_proto_api_proto protoreflect.FileDescriptor

const file_internal_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x18internal/proto/api.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cinternal/proto/cluster.proto\"9\n" +
	"\x10ListNodesRequest\x12%\n" +
	"\x06filter\x18\x01 \x01(\x0e2\r.proto.FilterR\x06filter\"\x9e\x01\n" +
	"\x11ListNodesResponse\x12+\n" +
	"\baccepted\x18\x01 \x03(\v2\x0f.proto.NodeInfoR\baccepted\x12/\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x0f.proto.NodeInfoR\n" +
	"candidates\x12+\n" +
	"\brejected\x18\x03 \x03(\v2\x0f.proto.NodeInfoR\brejected\"\xbb\x02\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\aaddress\x18\x02 \x01(\tH\x00R\aaddress\x88\x01\x01\x12%\n" +
	"\vcertificate\x18\x03 \x01(\tH\x01R\vcertificate\x88\x01\x01\x12%\n" +
	"\visConnected\x18\x04 \x01(\bH\x02R\visConnected\x88\x01\x01\x125\n" +
	"\x05since\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x05since\x88\x01\x01\x129\n" +
	"\alastMsg\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\alastMsg\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\x0e\n" +
	"\f_certificateB\x0e\n" +
	"\f_isConnectedB\b\n" +
	"\x06_sinceB\n" +
	"\n" +
	"\b_lastMsg\"2\n" +
	"\vNodeRequest\x12#\n" +
	"\x04node\x18\x01 \x01(\v2\x0f.proto.NodeInfoR\x04node\"3\n" +
	"\fNodeResponse\x12#\n" +
	"\x04node\x18\x01 \x01(\v2\x0f.proto.NodeInfoR\x04node\"6\n" +
	"\rNodesResponse\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.proto.NodeInfoR\x05nodes\",\n" +
	"\x0eResultsRequest\x12\x1a\n" +
	"\bresultID\x18\x01 \x01(\tR\bresultID\")\n" +
	"\x0fResultsResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\".\n" +
	"\x0eRequestRequest\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\"+\n" +
	"\x0fRequestResponse\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\"\xb6\x01\n" +
	"\x12ListResultsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12 \n" +
	"\tfrom_date\x18\x03 \x01(\x03H\x00R\bfromDate\x88\x01\x01\x12\x1c\n" +
	"\ato_date\x18\x04 \x01(\x03H\x01R\x06toDate\x88\x01\x01\x12\x18\n" +
	"\atargets\x18\x05 \x03(\tR\atargetsB\f\n" +
	"\n" +
	"_from_dateB\n" +
	"\n" +
	"\b_to_date\"\x9c\x01\n" +
	"\vResultEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12;\n" +
	"\x0einternal_error\x18\x04 \x01(\x0e2\x14.proto.InternalErrorR\rinternalError\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"C\n" +
	"\x13ListResultsResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.proto.ResultEntryR\aresults*M\n" +
	"\x06Filter\x12\b\n" +
	"\x04NONE\x10\x00\x12\x11\n" +
	"\rONLY_ACCEPTED\x10\x01\x12\x13\n" +
	"\x0fONLY_CANDIDATES\x10\x02\x12\x11\n" +
	"\rONLY_REJECTED\x10\x032\xeb\x04\n" +
	"\x03API\x12V\n" +
	"\tListNodes\x12\x17.proto.ListNodesRequest\x1a\x18.proto.ListNodesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/nodes/list\x12R\n" +
	"\n" +
	"AcceptNode\x12\x12.proto.NodeRequest\x1a\x13.proto.NodeResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/nodes/accept\x12P\n" +
	"\n" +
	"RemoveNode\x12\x12.proto.NodeRequest\x1a\x14.proto.NodesResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/nodes/remove\x12S\n" +
	"\n" +
	"RejectNode\x12\x12.proto.NodeRequest\x1a\x14.proto.NodesResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/nodes/reject\x12W\n" +
	"\n" +
	"GetResults\x12\x15.proto.ResultsRequest\x1a\x16.proto.ResultsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/results/result\x12^\n" +
	"\vListResults\x12\x19.proto.ListResultsRequest\x1a\x1a.proto.ListResultsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/results/list\x12X\n" +
	"\n" +
	"GetRequest\x12\x15.proto.RequestRequest\x1a\x16.proto.RequestResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/results/requestB.Z,github.com/kpetremann/jackadi/internal/protob\x06proto3"

var (
	file_internal_proto_api_proto_rawDescOnce sync.Once
	file_internal_proto_api_proto_rawDescData []byte
)

func file_internal_proto_api_proto_rawDescGZIP() []byte {
	file_internal_proto_api_proto_rawDescOnce.Do(func() {
		file_internal_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_api_proto_rawDesc), len(file_internal_proto_api_proto_rawDesc)))
	})
	return file_internal_proto_api_proto_rawDescData
}

var file_internal_proto_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_proto_api_proto_goTypes = []any{
	(Filter)(0),                   // 0: proto.Filter
	(*ListNodesRequest)(nil),      // 1: proto.ListNodesRequest
	(*ListNodesResponse)(nil),     // 2: proto.ListNodesResponse
	(*NodeInfo)(nil),              // 3: proto.NodeInfo
	(*NodeRequest)(nil),           // 4: proto.NodeRequest
	(*NodeResponse)(nil),          // 5: proto.NodeResponse
	(*NodesResponse)(nil),         // 6: proto.NodesResponse
	(*ResultsRequest)(nil),        // 7: proto.ResultsRequest
	(*ResultsResponse)(nil),       // 8: proto.ResultsResponse
	(*RequestRequest)(nil),        // 9: proto.RequestRequest
	(*RequestResponse)(nil),       // 10: proto.RequestResponse
	(*ListResultsRequest)(nil),    // 11: proto.ListResultsRequest
	(*ResultEntry)(nil),           // 12: proto.ResultEntry
	(*ListResultsResponse)(nil),   // 13: proto.ListResultsResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(InternalError)(0),            // 15: proto.InternalError
}
var file_internal_proto_api_proto_depIdxs = []int32{
	0,  // 0: proto.ListNodesRequest.filter:type_name -> proto.Filter
	3,  // 1: proto.ListNodesResponse.accepted:type_name -> proto.NodeInfo
	3,  // 2: proto.ListNodesResponse.candidates:type_name -> proto.NodeInfo
	3,  // 3: proto.ListNodesResponse.rejected:type_name -> proto.NodeInfo
	14, // 4: proto.NodeInfo.since:type_name -> google.protobuf.Timestamp
	14, // 5: proto.NodeInfo.lastMsg:type_name -> google.protobuf.Timestamp
	3,  // 6: proto.NodeRequest.node:type_name -> proto.NodeInfo
	3,  // 7: proto.NodeResponse.node:type_name -> proto.NodeInfo
	3,  // 8: proto.NodesResponse.nodes:type_name -> proto.NodeInfo
	15, // 9: proto.ResultEntry.internal_error:type_name -> proto.InternalError
	12, // 10: proto.ListResultsResponse.results:type_name -> proto.ResultEntry
	1,  // 11: proto.API.ListNodes:input_type -> proto.ListNodesRequest
	4,  // 12: proto.API.AcceptNode:input_type -> proto.NodeRequest
	4,  // 13: proto.API.RemoveNode:input_type -> proto.NodeRequest
	4,  // 14: proto.API.RejectNode:input_type -> proto.NodeRequest
	7,  // 15: proto.API.GetResults:input_type -> proto.ResultsRequest
	11, // 16: proto.API.ListResults:input_type -> proto.ListResultsRequest
	9,  // 17: proto.API.GetRequest:input_type -> proto.RequestRequest
	2,  // 18: proto.API.ListNodes:output_type -> proto.ListNodesResponse
	5,  // 19: proto.API.AcceptNode:output_type -> proto.NodeResponse
	6,  // 20: proto.API.RemoveNode:output_type -> proto.NodesResponse
	6,  // 21: proto.API.RejectNode:output_type -> proto.NodesResponse
	8,  // 22: proto.API.GetResults:output_type -> proto.ResultsResponse
	13, // 23: proto.API.ListResults:output_type -> proto.ListResultsResponse
	10, // 24: proto.API.GetRequest:output_type -> proto.RequestResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_proto_api_proto_init() }
func file_internal_proto_api_proto_init() {
	if File_internal_proto_api_proto != nil {
		return
	}
	file_internal_proto_cluster_proto_init()
	file_internal_proto_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_internal_proto_api_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_api_proto_rawDesc), len(file_internal_proto_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_api_proto_goTypes,
		DependencyIndexes: file_internal_proto_api_proto_depIdxs,
		EnumInfos:         file_internal_proto_api_proto_enumTypes,
		MessageInfos:      file_internal_proto_api_proto_msgTypes,
	}.Build()
	File_internal_proto_api_proto = out.File
	file_internal_proto_api_proto_goTypes = nil
	file_internal_proto_api_proto_depIdxs = nil
}
