syntax = "proto3";

package proto;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "internal/proto/cluster.proto";

option go_package = "github.com/kpetremann/jackadi/internal/proto";

service API {
  rpc ListNodes(ListNodesRequest) returns (ListNodesResponse) {
    option (google.api.http) = {
        get: "/v1/nodes/list"
    };
  }
  rpc AcceptNode(NodeRequest) returns (NodeResponse) {
    option (google.api.http) = {
      post: "/v1/nodes/accept"
      body: "*"
    };
  }
  rpc RemoveNode(NodeRequest) returns (NodesResponse) {
    option (google.api.http) = {delete: "/v1/nodes/remove"};
  }
  rpc RejectNode(NodeRequest) returns (NodesResponse) {
    option (google.api.http) = {
      post: "/v1/nodes/reject"
      body: "*"
    };
  }
  rpc GetResults(ResultsRequest) returns (ResultsResponse) {
    option (google.api.http) = {get: "/v1/results/result"};
  }
  rpc ListResults(ListResultsRequest) returns (ListResultsResponse) {
    option (google.api.http) = {get: "/v1/results/list"};
  }
  rpc GetRequest(RequestRequest) returns (RequestResponse) {
    option (google.api.http) = {get: "/v1/results/request"};
  }
}

message ListNodesRequest {
  Filter filter = 1;
}

enum Filter {
  NONE = 0;
  ONLY_ACCEPTED = 1;
  ONLY_CANDIDATES = 2;
  ONLY_REJECTED = 3;
}

message ListNodesResponse {
  repeated NodeInfo accepted = 1;
  repeated NodeInfo candidates = 2;
  repeated NodeInfo rejected = 3;
}

message NodeInfo {
  string id = 1;
  optional string address = 2;
  optional string certificate = 3;
  optional bool isConnected = 4;
  optional google.protobuf.Timestamp since = 5;
  optional google.protobuf.Timestamp lastMsg = 7;
}

message NodeRequest {
  NodeInfo node = 1;
}

message NodeResponse {
  NodeInfo node = 1;
}

message NodesResponse {
  repeated NodeInfo nodes = 1;
}

message ResultsRequest {
  string resultID = 1;
}

message ResultsResponse {
  string result = 1; // raw result, as stored in the DB (should be a serialized JSON)
}

message RequestRequest {
  string requestID = 1;
}

message RequestResponse {
  string request = 1; // raw request, as stored in the DB (should be a serialized JSON)
}

message ListResultsRequest {
  int32 offset = 1; // Starting position for pagination (0-based)
  int32 limit = 2; // Maximum number of results to return, defaults to 100 if not specified
  optional int64 from_date = 3; // Optional Unix timestamp to filter results from this date
  optional int64 to_date = 4; // Optional Unix timestamp to filter results up to this date
  repeated string targets = 5; // Optional list of node IDs to filter results by targets
}

message ResultEntry {
  int64 id = 1;
  string node = 2;
  string status = 3; // Status of the task (success, failed, error)
  InternalError internal_error = 4;
  string error = 5;
}

message ListResultsResponse {
  repeated ResultEntry results = 1;
}
