// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/proto/cluster.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalError int32

const (
	InternalError_OK              InternalError = 0
	InternalError_TIMEOUT         InternalError = 1
	InternalError_STARTED_TIMEOUT InternalError = 2
	InternalError_BUSY_QUEUE      InternalError = 3
	InternalError_FULL_QUEUE      InternalError = 4
	InternalError_UNKNOWN_TASK    InternalError = 5
	InternalError_MODULE_ERROR    InternalError = 6 // TODO: rename SDKError? PluginError? GRPCPluginError (GRPC between HC plugin and node)?
	InternalError_DISCONNECTING   InternalError = 7
	InternalError_DISCONNECTED    InternalError = 8
	InternalError_UNKNOWN_ERROR   InternalError = 9
)

// Enum value maps for InternalError.
var (
	InternalError_name = map[int32]string{
		0: "OK",
		1: "TIMEOUT",
		2: "STARTED_TIMEOUT",
		3: "BUSY_QUEUE",
		4: "FULL_QUEUE",
		5: "UNKNOWN_TASK",
		6: "MODULE_ERROR",
		7: "DISCONNECTING",
		8: "DISCONNECTED",
		9: "UNKNOWN_ERROR",
	}
	InternalError_value = map[string]int32{
		"OK":              0,
		"TIMEOUT":         1,
		"STARTED_TIMEOUT": 2,
		"BUSY_QUEUE":      3,
		"FULL_QUEUE":      4,
		"UNKNOWN_TASK":    5,
		"MODULE_ERROR":    6,
		"DISCONNECTING":   7,
		"DISCONNECTED":    8,
		"UNKNOWN_ERROR":   9,
	}
)

func (x InternalError) Enum() *InternalError {
	p := new(InternalError)
	*p = x
	return p
}

func (x InternalError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalError) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_cluster_proto_enumTypes[0].Descriptor()
}

func (InternalError) Type() protoreflect.EnumType {
	return &file_internal_proto_cluster_proto_enumTypes[0]
}

func (x InternalError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalError.Descriptor instead.
func (InternalError) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_cluster_proto_rawDescGZIP(), []int{0}
}

type TargetMode int32

const (
	TargetMode_UNKNOWN TargetMode = 0
	TargetMode_EXACT   TargetMode = 1
	TargetMode_LIST    TargetMode = 2
	TargetMode_GLOB    TargetMode = 3
	TargetMode_REGEX   TargetMode = 4
	TargetMode_QUERY   TargetMode = 5
)

// Enum value maps for TargetMode.
var (
	TargetMode_name = map[int32]string{
		0: "UNKNOWN",
		1: "EXACT",
		2: "LIST",
		3: "GLOB",
		4: "REGEX",
		5: "QUERY",
	}
	TargetMode_value = map[string]int32{
		"UNKNOWN": 0,
		"EXACT":   1,
		"LIST":    2,
		"GLOB":    3,
		"REGEX":   4,
		"QUERY":   5,
	}
)

func (x TargetMode) Enum() *TargetMode {
	p := new(TargetMode)
	*p = x
	return p
}

func (x TargetMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_cluster_proto_enumTypes[1].Descriptor()
}

func (TargetMode) Type() protoreflect.EnumType {
	return &file_internal_proto_cluster_proto_enumTypes[1]
}

func (x TargetMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetMode.Descriptor instead.
func (TargetMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_cluster_proto_rawDescGZIP(), []int{1}
}

type LockMode int32

const (
	LockMode_UNSPECIFIED LockMode = 0
	LockMode_NO_LOCK     LockMode = 1
	LockMode_WRITE       LockMode = 2
	LockMode_EXCLUSIVE   LockMode = 3
)

// Enum value maps for LockMode.
var (
	LockMode_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NO_LOCK",
		2: "WRITE",
		3: "EXCLUSIVE",
	}
	LockMode_value = map[string]int32{
		"UNSPECIFIED": 0,
		"NO_LOCK":     1,
		"WRITE":       2,
		"EXCLUSIVE":   3,
	}
)

func (x LockMode) Enum() *LockMode {
	p := new(LockMode)
	*p = x
	return p
}

func (x LockMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LockMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_cluster_proto_enumTypes[2].Descriptor()
}

func (LockMode) Type() protoreflect.EnumType {
	return &file_internal_proto_cluster_proto_enumTypes[2]
}

func (x LockMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LockMode.Descriptor instead.
func (LockMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_cluster_proto_rawDescGZIP(), []int{2}
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_internal_proto_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_internal_proto_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupID       *int64                 `protobuf:"varint,2,opt,name=groupID,proto3,oneof" json:"groupID,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	TargetMode    TargetMode             `protobuf:"varint,4,opt,name=target_mode,json=targetMode,proto3,enum=proto.TargetMode" json:"target_mode,omitempty"`
	LockMode      LockMode               `protobuf:"varint,5,opt,name=lock_mode,json=lockMode,proto3,enum=proto.LockMode" json:"lock_mode,omitempty"`
	Timeout       uint32                 `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Task          string                 `protobuf:"bytes,7,opt,name=task,proto3" json:"task,omitempty"`
	Input         *Input                 `protobuf:"bytes,8,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_internal_proto_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *TaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskRequest) GetGroupID() int64 {
	if x != nil && x.GroupID != nil {
		return *x.GroupID
	}
	return 0
}

func (x *TaskRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TaskRequest) GetTargetMode() TargetMode {
	if x != nil {
		return x.TargetMode
	}
	return TargetMode_UNKNOWN
}

func (x *TaskRequest) GetLockMode() LockMode {
	if x != nil {
		return x.LockMode
	}
	return LockMode_UNSPECIFIED
}

func (x *TaskRequest) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *TaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *TaskRequest) GetInput() *Input {
	if x != nil {
		return x.Input
	}
	return nil
}

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          *structpb.ListValue    `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	Options       *structpb.Struct       `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_internal_proto_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_internal_proto_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *Input) GetArgs() *structpb.ListValue {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Input) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupID       *int64                 `protobuf:"varint,2,opt,name=groupID,proto3,oneof" json:"groupID,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Retcode       int32                  `protobuf:"varint,5,opt,name=retcode,proto3" json:"retcode,omitempty"`                                      // TODO: remove
	InternalError InternalError          `protobuf:"varint,6,opt,name=internalError,proto3,enum=proto.InternalError" json:"internalError,omitempty"` // Could be the global error type ( != OK when the task returned an error)
	ModuleError   string                 `protobuf:"bytes,7,opt,name=moduleError,proto3" json:"moduleError,omitempty"`                               // TODO: rename SDKError? PluginError? GRPCPluginError (GRPC between HC plugin and node)?, or InternalErrorMsg. Can it be merged with error?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_internal_proto_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskResponse) GetGroupID() int64 {
	if x != nil && x.GroupID != nil {
		return *x.GroupID
	}
	return 0
}

func (x *TaskResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResponse) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *TaskResponse) GetInternalError() InternalError {
	if x != nil {
		return x.InternalError
	}
	return InternalError_OK
}

func (x *TaskResponse) GetModuleError() string {
	if x != nil {
		return x.ModuleError
	}
	return ""
}

type FwdResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Responses     map[string]*TaskResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FwdResponse) Reset() {
	*x = FwdResponse{}
	mi := &file_internal_proto_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FwdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FwdResponse) ProtoMessage() {}

func (x *FwdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FwdResponse.ProtoReflect.Descriptor instead.
func (*FwdResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *FwdResponse) GetResponses() map[string]*TaskResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ListNodePluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        map[string]string      `protobuf:"bytes,1,rep,name=plugin,proto3" json:"plugin,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key=filename, value=checksum
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodePluginsResponse) Reset() {
	*x = ListNodePluginsResponse{}
	mi := &file_internal_proto_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodePluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodePluginsResponse) ProtoMessage() {}

func (x *ListNodePluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodePluginsResponse.ProtoReflect.Descriptor instead.
func (*ListNodePluginsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodePluginsResponse) GetPlugin() map[string]string {
	if x != nil {
		return x.Plugin
	}
	return nil
}

var File_internal_proto_cluster_proto protoreflect.FileDescriptor

const file_internal_proto_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/cluster.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\"\n" +
	"\x10HandshakeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11HandshakeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x94\x02\n" +
	"\vTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\agroupID\x18\x02 \x01(\x03H\x00R\agroupID\x88\x01\x01\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x122\n" +
	"\vtarget_mode\x18\x04 \x01(\x0e2\x11.proto.TargetModeR\n" +
	"targetMode\x12,\n" +
	"\tlock_mode\x18\x05 \x01(\x0e2\x0f.proto.LockModeR\blockMode\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\rR\atimeout\x12\x12\n" +
	"\x04task\x18\a \x01(\tR\x04task\x12\"\n" +
	"\x05input\x18\b \x01(\v2\f.proto.InputR\x05inputB\n" +
	"\n" +
	"\b_groupID\"j\n" +
	"\x05Input\x12.\n" +
	"\x04args\x18\x01 \x01(\v2\x1a.google.protobuf.ListValueR\x04args\x121\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.google.protobuf.StructR\aoptions\"\xef\x01\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\agroupID\x18\x02 \x01(\x03H\x00R\agroupID\x88\x01\x01\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x18\n" +
	"\aretcode\x18\x05 \x01(\x05R\aretcode\x12:\n" +
	"\rinternalError\x18\x06 \x01(\x0e2\x14.proto.InternalErrorR\rinternalError\x12 \n" +
	"\vmoduleError\x18\a \x01(\tR\vmoduleErrorB\n" +
	"\n" +
	"\b_groupID\"\xa1\x01\n" +
	"\vFwdResponse\x12?\n" +
	"\tresponses\x18\x01 \x03(\v2!.proto.FwdResponse.ResponsesEntryR\tresponses\x1aQ\n" +
	"\x0eResponsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proto.TaskResponseR\x05value:\x028\x01\"\x98\x01\n" +
	"\x17ListNodePluginsResponse\x12B\n" +
	"\x06plugin\x18\x01 \x03(\v2*.proto.ListNodePluginsResponse.PluginEntryR\x06plugin\x1a9\n" +
	"\vPluginEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xb5\x01\n" +
	"\rInternalError\x12\x06\n" +
	"\x02OK\x10\x00\x12\v\n" +
	"\aTIMEOUT\x10\x01\x12\x13\n" +
	"\x0fSTARTED_TIMEOUT\x10\x02\x12\x0e\n" +
	"\n" +
	"BUSY_QUEUE\x10\x03\x12\x0e\n" +
	"\n" +
	"FULL_QUEUE\x10\x04\x12\x10\n" +
	"\fUNKNOWN_TASK\x10\x05\x12\x10\n" +
	"\fMODULE_ERROR\x10\x06\x12\x11\n" +
	"\rDISCONNECTING\x10\a\x12\x10\n" +
	"\fDISCONNECTED\x10\b\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\t*N\n" +
	"\n" +
	"TargetMode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05EXACT\x10\x01\x12\b\n" +
	"\x04LIST\x10\x02\x12\b\n" +
	"\x04GLOB\x10\x03\x12\t\n" +
	"\x05REGEX\x10\x04\x12\t\n" +
	"\x05QUERY\x10\x05*B\n" +
	"\bLockMode\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aNO_LOCK\x10\x01\x12\t\n" +
	"\x05WRITE\x10\x02\x12\r\n" +
	"\tEXCLUSIVE\x10\x032\xcd\x01\n" +
	"\aCluster\x12>\n" +
	"\tHandshake\x12\x17.proto.HandshakeRequest\x1a\x18.proto.HandshakeResponse\x127\n" +
	"\bExecTask\x12\x13.proto.TaskResponse\x1a\x12.proto.TaskRequest(\x010\x01\x12I\n" +
	"\x0fListNodePlugins\x12\x16.google.protobuf.Empty\x1a\x1e.proto.ListNodePluginsResponse2Y\n" +
	"\tForwarder\x12L\n" +
	"\bExecTask\x12\x12.proto.TaskRequest\x1a\x12.proto.FwdResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/task/execB.Z,github.com/kpetremann/jackadi/internal/protob\x06proto3"

var (
	file_internal_proto_cluster_proto_rawDescOnce sync.Once
	file_internal_proto_cluster_proto_rawDescData []byte
)

func file_internal_proto_cluster_proto_rawDescGZIP() []byte {
	file_internal_proto_cluster_proto_rawDescOnce.Do(func() {
		file_internal_proto_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_cluster_proto_rawDesc), len(file_internal_proto_cluster_proto_rawDesc)))
	})
	return file_internal_proto_cluster_proto_rawDescData
}

var file_internal_proto_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_proto_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_proto_cluster_proto_goTypes = []any{
	(InternalError)(0),              // 0: proto.InternalError
	(TargetMode)(0),                 // 1: proto.TargetMode
	(LockMode)(0),                   // 2: proto.LockMode
	(*HandshakeRequest)(nil),        // 3: proto.HandshakeRequest
	(*HandshakeResponse)(nil),       // 4: proto.HandshakeResponse
	(*TaskRequest)(nil),             // 5: proto.TaskRequest
	(*Input)(nil),                   // 6: proto.Input
	(*TaskResponse)(nil),            // 7: proto.TaskResponse
	(*FwdResponse)(nil),             // 8: proto.FwdResponse
	(*ListNodePluginsResponse)(nil), // 9: proto.ListNodePluginsResponse
	nil,                             // 10: proto.FwdResponse.ResponsesEntry
	nil,                             // 11: proto.ListNodePluginsResponse.PluginEntry
	(*structpb.ListValue)(nil),      // 12: google.protobuf.ListValue
	(*structpb.Struct)(nil),         // 13: google.protobuf.Struct
	(*emptypb.Empty)(nil),           // 14: google.protobuf.Empty
}
var file_internal_proto_cluster_proto_depIdxs = []int32{
	1,  // 0: proto.TaskRequest.target_mode:type_name -> proto.TargetMode
	2,  // 1: proto.TaskRequest.lock_mode:type_name -> proto.LockMode
	6,  // 2: proto.TaskRequest.input:type_name -> proto.Input
	12, // 3: proto.Input.args:type_name -> google.protobuf.ListValue
	13, // 4: proto.Input.options:type_name -> google.protobuf.Struct
	0,  // 5: proto.TaskResponse.internalError:type_name -> proto.InternalError
	10, // 6: proto.FwdResponse.responses:type_name -> proto.FwdResponse.ResponsesEntry
	11, // 7: proto.ListNodePluginsResponse.plugin:type_name -> proto.ListNodePluginsResponse.PluginEntry
	7,  // 8: proto.FwdResponse.ResponsesEntry.value:type_name -> proto.TaskResponse
	3,  // 9: proto.Cluster.Handshake:input_type -> proto.HandshakeRequest
	7,  // 10: proto.Cluster.ExecTask:input_type -> proto.TaskResponse
	14, // 11: proto.Cluster.ListNodePlugins:input_type -> google.protobuf.Empty
	5,  // 12: proto.Forwarder.ExecTask:input_type -> proto.TaskRequest
	4,  // 13: proto.Cluster.Handshake:output_type -> proto.HandshakeResponse
	5,  // 14: proto.Cluster.ExecTask:output_type -> proto.TaskRequest
	9,  // 15: proto.Cluster.ListNodePlugins:output_type -> proto.ListNodePluginsResponse
	8,  // 16: proto.Forwarder.ExecTask:output_type -> proto.FwdResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_proto_cluster_proto_init() }
func file_internal_proto_cluster_proto_init() {
	if File_internal_proto_cluster_proto != nil {
		return
	}
	file_internal_proto_cluster_proto_msgTypes[2].OneofWrappers = []any{}
	file_internal_proto_cluster_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_cluster_proto_rawDesc), len(file_internal_proto_cluster_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_proto_cluster_proto_goTypes,
		DependencyIndexes: file_internal_proto_cluster_proto_depIdxs,
		EnumInfos:         file_internal_proto_cluster_proto_enumTypes,
		MessageInfos:      file_internal_proto_cluster_proto_msgTypes,
	}.Build()
	File_internal_proto_cluster_proto = out.File
	file_internal_proto_cluster_proto_goTypes = nil
	file_internal_proto_cluster_proto_depIdxs = nil
}
