// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/plugin/core/protoplugin/plugin.proto

package protoplugin

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	proto "github.com/kpetremann/jackadi/internal/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameResponse) Reset() {
	*x = NameResponse{}
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameResponse) ProtoMessage() {}

func (x *NameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameResponse.ProtoReflect.Descriptor instead.
func (*NameResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *NameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksResponse) Reset() {
	*x = TasksResponse{}
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksResponse) ProtoMessage() {}

func (x *TasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksResponse.ProtoReflect.Descriptor instead.
func (*TasksResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *TasksResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type HelpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelpRequest) Reset() {
	*x = HelpRequest{}
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelpRequest) ProtoMessage() {}

func (x *HelpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelpRequest.ProtoReflect.Descriptor instead.
func (*HelpRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *HelpRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type HelpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        map[string]string      `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelpResponse) Reset() {
	*x = HelpResponse{}
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelpResponse) ProtoMessage() {}

func (x *HelpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelpResponse.ProtoReflect.Descriptor instead.
func (*HelpResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HelpResponse) GetOutput() map[string]string {
	if x != nil {
		return x.Output
	}
	return nil
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginVersion string                 `protobuf:"bytes,1,opt,name=PluginVersion,proto3" json:"PluginVersion,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=Commit,proto3" json:"Commit,omitempty"`
	BuildTime     string                 `protobuf:"bytes,3,opt,name=BuildTime,proto3" json:"BuildTime,omitempty"`
	GoVersion     string                 `protobuf:"bytes,4,opt,name=GoVersion,proto3" json:"GoVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *VersionResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *VersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *VersionResponse) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *VersionResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

type DoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Input         *proto.Input           `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoRequest) Reset() {
	*x = DoRequest{}
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoRequest) ProtoMessage() {}

func (x *DoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoRequest.ProtoReflect.Descriptor instead.
func (*DoRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *DoRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *DoRequest) GetInput() *proto.Input {
	if x != nil {
		return x.Input
	}
	return nil
}

type DoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Retcode       int32                  `protobuf:"varint,3,opt,name=retcode,proto3" json:"retcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoResponse) Reset() {
	*x = DoResponse{}
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoResponse) ProtoMessage() {}

func (x *DoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoResponse.ProtoReflect.Descriptor instead.
func (*DoResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *DoResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *DoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DoResponse) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

type CollectSpecsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectSpecsResponse) Reset() {
	*x = CollectSpecsResponse{}
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectSpecsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectSpecsResponse) ProtoMessage() {}

func (x *CollectSpecsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectSpecsResponse.ProtoReflect.Descriptor instead.
func (*CollectSpecsResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *CollectSpecsResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *CollectSpecsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskLockModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLockModeRequest) Reset() {
	*x = TaskLockModeRequest{}
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLockModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLockModeRequest) ProtoMessage() {}

func (x *TaskLockModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLockModeRequest.ProtoReflect.Descriptor instead.
func (*TaskLockModeRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *TaskLockModeRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type TaskLockModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockMode      proto.LockMode         `protobuf:"varint,1,opt,name=lock_mode,json=lockMode,proto3,enum=proto.LockMode" json:"lock_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLockModeResponse) Reset() {
	*x = TaskLockModeResponse{}
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLockModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLockModeResponse) ProtoMessage() {}

func (x *TaskLockModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_core_protoplugin_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLockModeResponse.ProtoReflect.Descriptor instead.
func (*TaskLockModeResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *TaskLockModeResponse) GetLockMode() proto.LockMode {
	if x != nil {
		return x.LockMode
	}
	return proto.LockMode(0)
}

var File_internal_plugin_core_protoplugin_plugin_proto protoreflect.FileDescriptor

const file_internal_plugin_core_protoplugin_plugin_proto_rawDesc = "" +
	"\n" +
	"-internal/plugin/core/protoplugin/plugin.proto\x12\vprotoplugin\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cinternal/proto/cluster.proto\"\"\n" +
	"\fNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"%\n" +
	"\rTasksResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"!\n" +
	"\vHelpRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\"\x88\x01\n" +
	"\fHelpResponse\x12=\n" +
	"\x06output\x18\x01 \x03(\v2%.protoplugin.HelpResponse.OutputEntryR\x06output\x1a9\n" +
	"\vOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\x0fVersionResponse\x12$\n" +
	"\rPluginVersion\x18\x01 \x01(\tR\rPluginVersion\x12\x16\n" +
	"\x06Commit\x18\x02 \x01(\tR\x06Commit\x12\x1c\n" +
	"\tBuildTime\x18\x03 \x01(\tR\tBuildTime\x12\x1c\n" +
	"\tGoVersion\x18\x04 \x01(\tR\tGoVersion\"C\n" +
	"\tDoRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\"\n" +
	"\x05input\x18\x02 \x01(\v2\f.proto.InputR\x05input\"T\n" +
	"\n" +
	"DoResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aretcode\x18\x03 \x01(\x05R\aretcode\"D\n" +
	"\x14CollectSpecsResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x13TaskLockModeRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\"D\n" +
	"\x14TaskLockModeResponse\x12,\n" +
	"\tlock_mode\x18\x01 \x01(\x0e2\x0f.proto.LockModeR\blockMode2\xdf\x03\n" +
	"\rJackadiPlugin\x129\n" +
	"\x04Name\x12\x16.google.protobuf.Empty\x1a\x19.protoplugin.NameResponse\x12;\n" +
	"\x05Tasks\x12\x16.google.protobuf.Empty\x1a\x1a.protoplugin.TasksResponse\x12;\n" +
	"\x04Help\x12\x18.protoplugin.HelpRequest\x1a\x19.protoplugin.HelpResponse\x12?\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a\x1c.protoplugin.VersionResponse\x125\n" +
	"\x02Do\x12\x16.protoplugin.DoRequest\x1a\x17.protoplugin.DoResponse\x12I\n" +
	"\fCollectSpecs\x12\x16.google.protobuf.Empty\x1a!.protoplugin.CollectSpecsResponse\x12V\n" +
	"\x0fGetTaskLockMode\x12 .protoplugin.TaskLockModeRequest\x1a!.protoplugin.TaskLockModeResponseB6Z4github.com/kpetremann/jackadi/pkg/plugin/protopluginb\x06proto3"

var (
	file_internal_plugin_core_protoplugin_plugin_proto_rawDescOnce sync.Once
	file_internal_plugin_core_protoplugin_plugin_proto_rawDescData []byte
)

func file_internal_plugin_core_protoplugin_plugin_proto_rawDescGZIP() []byte {
	file_internal_plugin_core_protoplugin_plugin_proto_rawDescOnce.Do(func() {
		file_internal_plugin_core_protoplugin_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugin_core_protoplugin_plugin_proto_rawDesc), len(file_internal_plugin_core_protoplugin_plugin_proto_rawDesc)))
	})
	return file_internal_plugin_core_protoplugin_plugin_proto_rawDescData
}

var file_internal_plugin_core_protoplugin_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_plugin_core_protoplugin_plugin_proto_goTypes = []any{
	(*NameResponse)(nil),         // 0: protoplugin.NameResponse
	(*TasksResponse)(nil),        // 1: protoplugin.TasksResponse
	(*HelpRequest)(nil),          // 2: protoplugin.HelpRequest
	(*HelpResponse)(nil),         // 3: protoplugin.HelpResponse
	(*VersionResponse)(nil),      // 4: protoplugin.VersionResponse
	(*DoRequest)(nil),            // 5: protoplugin.DoRequest
	(*DoResponse)(nil),           // 6: protoplugin.DoResponse
	(*CollectSpecsResponse)(nil), // 7: protoplugin.CollectSpecsResponse
	(*TaskLockModeRequest)(nil),  // 8: protoplugin.TaskLockModeRequest
	(*TaskLockModeResponse)(nil), // 9: protoplugin.TaskLockModeResponse
	nil,                          // 10: protoplugin.HelpResponse.OutputEntry
	(*proto.Input)(nil),          // 11: proto.Input
	(proto.LockMode)(0),          // 12: proto.LockMode
	(*emptypb.Empty)(nil),        // 13: google.protobuf.Empty
}
var file_internal_plugin_core_protoplugin_plugin_proto_depIdxs = []int32{
	10, // 0: protoplugin.HelpResponse.output:type_name -> protoplugin.HelpResponse.OutputEntry
	11, // 1: protoplugin.DoRequest.input:type_name -> proto.Input
	12, // 2: protoplugin.TaskLockModeResponse.lock_mode:type_name -> proto.LockMode
	13, // 3: protoplugin.JackadiPlugin.Name:input_type -> google.protobuf.Empty
	13, // 4: protoplugin.JackadiPlugin.Tasks:input_type -> google.protobuf.Empty
	2,  // 5: protoplugin.JackadiPlugin.Help:input_type -> protoplugin.HelpRequest
	13, // 6: protoplugin.JackadiPlugin.Version:input_type -> google.protobuf.Empty
	5,  // 7: protoplugin.JackadiPlugin.Do:input_type -> protoplugin.DoRequest
	13, // 8: protoplugin.JackadiPlugin.CollectSpecs:input_type -> google.protobuf.Empty
	8,  // 9: protoplugin.JackadiPlugin.GetTaskLockMode:input_type -> protoplugin.TaskLockModeRequest
	0,  // 10: protoplugin.JackadiPlugin.Name:output_type -> protoplugin.NameResponse
	1,  // 11: protoplugin.JackadiPlugin.Tasks:output_type -> protoplugin.TasksResponse
	3,  // 12: protoplugin.JackadiPlugin.Help:output_type -> protoplugin.HelpResponse
	4,  // 13: protoplugin.JackadiPlugin.Version:output_type -> protoplugin.VersionResponse
	6,  // 14: protoplugin.JackadiPlugin.Do:output_type -> protoplugin.DoResponse
	7,  // 15: protoplugin.JackadiPlugin.CollectSpecs:output_type -> protoplugin.CollectSpecsResponse
	9,  // 16: protoplugin.JackadiPlugin.GetTaskLockMode:output_type -> protoplugin.TaskLockModeResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_plugin_core_protoplugin_plugin_proto_init() }
func file_internal_plugin_core_protoplugin_plugin_proto_init() {
	if File_internal_plugin_core_protoplugin_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugin_core_protoplugin_plugin_proto_rawDesc), len(file_internal_plugin_core_protoplugin_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_plugin_core_protoplugin_plugin_proto_goTypes,
		DependencyIndexes: file_internal_plugin_core_protoplugin_plugin_proto_depIdxs,
		MessageInfos:      file_internal_plugin_core_protoplugin_plugin_proto_msgTypes,
	}.Build()
	File_internal_plugin_core_protoplugin_plugin_proto = out.File
	file_internal_plugin_core_protoplugin_plugin_proto_goTypes = nil
	file_internal_plugin_core_protoplugin_plugin_proto_depIdxs = nil
}
